# Generated by Django 5.0.7 on 2024-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0002_tradedetails_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradedetails",
            name="pnl",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
